// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using CvPipeline.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CvPipeline.Api.Migrations
{
    [DbContext(typeof(CvPipelineDbContext))]
    [Migration("20260722040056_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CvPipeline.Api.Models.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CvSourceFilename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cv_source_filename");

                    b.Property<string>("CvText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cv_text");

                    b.Property<JsonDocument>("Document")
                        .HasColumnType("jsonb")
                        .HasColumnName("document");

                    b.Property<JsonDocument>("FailureDetail")
                        .HasColumnType("jsonb")
                        .HasColumnName("failure_detail");

                    b.Property<string>("JobRequirements")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_requirements");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<JsonDocument>("Warnings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("warnings")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "analyses_created_at_idx")
                        .IsDescending();

                    b.ToTable("analyses", null, t =>
                        {
                            t.HasCheckConstraint("analyses_status_check", "status IN ('extracting','tailoring','review','generated','failed')");
                        });
                });

            modelBuilder.Entity("CvPipeline.Api.Models.Generation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("OutputFilename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("output_filename");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_title");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AnalysisId" }, "generations_analysis_idx");

                    b.HasIndex(new[] { "CreatedAt" }, "generations_created_at_idx")
                        .IsDescending();

                    b.ToTable("generations", (string)null);
                });

            modelBuilder.Entity("CvPipeline.Api.Models.GenerationField", b =>
                {
                    b.Property<Guid>("GenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_id");

                    b.Property<string>("FieldPath")
                        .HasColumnType("text")
                        .HasColumnName("field_path");

                    b.PrimitiveCollection<List<string>>("Criteria")
                        .HasColumnType("text[]")
                        .HasColumnName("criteria");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provenance");

                    b.PrimitiveCollection<List<string>>("RuleIds")
                        .HasColumnType("text[]")
                        .HasColumnName("rule_ids");

                    b.Property<JsonDocument>("SourceQuotes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_quotes")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("GenerationId", "FieldPath");

                    b.HasIndex(new[] { "Provenance" }, "generation_fields_provenance_idx");

                    b.HasIndex(new[] { "RuleIds" }, "generation_fields_rule_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "RuleIds" }, "generation_fields_rule_idx"), "gin");

                    b.ToTable("generation_fields", null, t =>
                        {
                            t.HasCheckConstraint("absent_has_no_sources", "provenance <> 'absent' OR source_quotes = '[]'::jsonb");

                            t.HasCheckConstraint("generation_fields_provenance_check", "provenance IN ('verbatim','normalised','derived','generated','edited','absent')");

                            t.HasCheckConstraint("normalised_cites_at_least_one_rule", "provenance <> 'normalised' OR (rule_ids IS NOT NULL AND array_length(rule_ids, 1) > 0)");
                        });
                });

            modelBuilder.Entity("CvPipeline.Api.Models.Generation", b =>
                {
                    b.HasOne("CvPipeline.Api.Models.Analysis", "Analysis")
                        .WithMany("Generations")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("CvPipeline.Api.Models.GenerationField", b =>
                {
                    b.HasOne("CvPipeline.Api.Models.Generation", "Generation")
                        .WithMany("GenerationFields")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("CvPipeline.Api.Models.Analysis", b =>
                {
                    b.Navigation("Generations");
                });

            modelBuilder.Entity("CvPipeline.Api.Models.Generation", b =>
                {
                    b.Navigation("GenerationFields");
                });
#pragma warning restore 612, 618
        }
    }
}
